name: mechanicum
description: "Mechanicum - Your Personal Mission Tracker"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '^3.7.2'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.1
  flutter_spinkit: ^5.2.1
  media_kit_video: ^1.3.0
  pinput: ^5.0.1
  path_provider: ^2.1.4
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  flutter_gif: ^0.0.4
  intl: ^0.20.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  shared_preferences: ^2.2.0
  fl_chart: ^0.68.0
  provider: ^6.0.0
  lottie: ^2.0.0
  hive: ^2.2.3
  image_picker: ^1.1.2
  app_badge_plus: ^1.2.3
  flutter_local_notifications: ^19.3.0
  image: ^4.2.0
  palette_generator: ^0.3.3+7
  permission_handler: ^12.0.0+1
  flutter_secure_storage: ^9.2.4
  flutter_timezone: ^4.1.0
  timezone: ^0.10.1
  flutter_background_service: ^5.1.0
  flutter_launcher_icons: ^0.14.3
  mockito: ^5.4.4
  path: ^1.9.1
  queue: ^3.4.0
  synchronized: ^3.3.1
  mermaid: ^0.9.35
  flutter_svg: ^2.0.10
  workmanager: ^0.7.0
  timeago: ^3.7.1
  flutter_highlight: ^0.7.0
  http: ^1.4.0
  socket_io_client: ^3.1.2
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  device_info_plus: ^11.5.0
  webview_flutter: ^4.13.0
  fast_noise: ^2.0.0
  # flutter_eval: ^0.7.8
  simple_animation_progress_bar: ^1.9.2
  wave: ^0.2.2
  flutter_colorpicker: ^1.1.0
  flutter_rating_bar: ^4.0.1
  matrix_digital_rain: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gif/
    - assets/video/
    - assets/config/dynamic_config.json
    - assets/video/1.mov
    - assets/video/0421.mp4
    - assets/gif/goku_idle.gif
    - assets/gif/goku_blue.gif
    - assets/gif/intro_anime.gif
    - assets/gif/goku_intro.gif
    - assets/gif/_goku.jpg
    - assets/gif/mad_uchiha.gif
    - assets/gif/vegeta.gif
    - assets/gif/guts.gif
    - assets/gif/mad_dash.gif
    - assets/gif/warhammer_titus.gif
    - assets/gif/codex.gif
    - images/88.jpeg
    - images/imag1.jpeg
    - images/berserk_red.jpeg
    - images/clouds.jpeg
    - images/gas_station.jpeg
    - images/horus.jpeg
    - images/idea_one.jpeg
    - images/idea_two.jpeg
    - images/idea_three.jpeg
    - images/idea_four.jpeg
    - images/idea_six.jpeg
    - images/pic_one.jpeg
    - images/pic_two.jpeg
    - images/pic_three.jpeg
    - images/pic.jpeg
    - images/gmeboy.jpeg
    - images/new_pic.jpeg
    - images/random.jpeg
    - images/picture.jpeg
    - images/sky.jpeg
    - images/image.jpeg
    - images/cam.jpeg
    - images/butters.jpeg
    - images/eric.jpeg
    - images/cartman.jpeg
    - images/kyle.jpeg
    - images/kenny.jpeg
    - images/skull_flow.jpeg
    - images/bike.jpeg
    - images/madara.jpeg
    - images/quote.jpeg
    - images/kakashi.jpeg
    - images/neon.jpeg
    - images/kame.jpeg
    - images/madara_two.jpeg
    - images/peace.jpeg
    - images/unknown.jpeg
    - images/vinland.jpeg
    - images/quote_two.jpeg
    - images/icarus.jpeg
    - images/guts_peace.jpeg
    - images/images23.jpeg
    - images/tkyo.jpeg
    - images/tokyo_blsm.jpeg
    - images/guts_sword.jpeg
    - images/gohan.jpeg
    - images/scene.jpeg
    - images/scene_2.jpeg 
    - images/villans.jpeg
    - images/focus.jpeg
    - images/rage.jpeg
    - images/tranquil.jpeg
    - assets/gif/adventure_time.gif

   



  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
