# Railway Configuration for AI Backend - UNIFIED SETUP
[build]
builder = "NIXPACKS"

[deploy]
<<<<<<< HEAD
# CRITICAL: Use $PORT environment variable that Railway provides
startCommand = "uvicorn main_unified:app --host 0.0.0.0 --port $PORT --log-level info"
healthcheckPath = "/ping"
healthcheckTimeout = 60
=======
startCommand = "python main_unified.py"
healthcheckPath = "/ping"
healthcheckTimeout = 180
>>>>>>> c1d6a8c31bb147cf04e369e7feb719bc9a020e24
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Railway automatically sets PORT environment variable - don't override it
# [environments.production]
# [environments.staging]