# Railway Configuration for AI Backend - UNIFIED SETUP
[build]
builder = "NIXPACKS"

[deploy]
# Use startup script that properly handles PORT environment variable
startCommand = "./railway_start.sh"
healthcheckPath = "/ping"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Railway automatically sets PORT environment variable - don't override it
# [environments.production]
# [environments.staging]