# Railway Configuration for AI Backend with Project Horus & Berserk
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn main_unified:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
RUN_BACKGROUND_JOBS = "1"
PORT = "8000"
# Project Horus & Berserk are included in main_unified.py and ready for deployment

[environments.staging]  
RUN_BACKGROUND_JOBS = "1"
PORT = "8000"
# All 53 endpoints (6 Horus + 47 Berserk) are included and tested