# Railway Configuration for AI Backend with Project Horus & Berserk
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main_unified.py"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
RUN_BACKGROUND_JOBS = "1"
# Railway will set PORT automatically
# Project Horus & Berserk are included in main_unified.py and ready for deployment

[environments.staging]  
RUN_BACKGROUND_JOBS = "1"
# Railway will set PORT automatically
# All 53 endpoints (6 Horus + 47 Berserk) are included and tested