name: Test GitHub Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
      
      - name: Test Connection
        run: |
          echo "Testing SSH connection..."
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
          ssh ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} "echo 'Connection successful!'"
      
      - name: Show Secrets Status
        run: |
          echo "AWS_HOST: ${{ secrets.AWS_HOST }}"
          echo "AWS_USER: ${{ secrets.AWS_USER }}"
          echo "AWS_SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY != '' && 'SET' || 'NOT SET' }}" 