# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python -m uvicorn main_unified:app --host 0.0.0.0 --port ${PORT:-8000}"