# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["python312", "gcc", "curl"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
# CRITICAL: Use $PORT environment variable that Railway provides
cmd = "uvicorn main_unified:app --host 0.0.0.0 --port $PORT --log-level info"