# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "chmod +x start.sh && ./start.sh"