services:
  - type: web
    name: ai-backend-python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        value: your_neon_postgresql_url
      - key: ANTHROPIC_API_KEY
        value: your_anthropic_api_key
      - key: OPENAI_API_KEY
        value: your_openai_api_key
      - key: GITHUB_TOKEN
        value: your_github_token
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: RUN_BACKGROUND_JOBS
        value: 1 