import 'package:hive/hive.dart';

part 'entry.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 0)
class Entry {
  @HiveField(0)
  final int id;

  @HiveField(1)
  final String title;

  @HiveField(2)
  final String content;

  @HiveField(3)
  final String imageUrl;

  @HiveField(4)
  final String createdAt;

  Entry({
    required this.id,
    required this.title,
    required this.content,
    required this.imageUrl,
    required this.createdAt,
  });

  Entry.fromJson(Map<String, dynamic> json)
    : id = json['id'],
      title = json['title'],
      content = json['content'],
      imageUrl = json['image_url'],
      createdAt = json['created_at'].toString();
}
