name: Deploy Backend to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: Add AWS to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS via SSH
        run: |
          ssh ${{ secrets.AWS_USER }}@${{ secrets.AWS_HOST }} '
            cd /home/ubuntu/ai-backend &&
            git pull origin master &&
            npm install &&
            pm2 restart all || pm2 start src/index.js --name ai-backend
          '

# ---
# Required GitHub secrets:
#   AWS_SSH_PRIVATE_KEY: Your private SSH key for the AWS server
#   AWS_HOST: The public IP or DNS of your AWS server (e.g., 44.204.184.21)
#   AWS_USER: The SSH username (e.g., ubuntu)
#
# To set up:
# 1. Generate an SSH key (if you don't have one):
#    ssh-keygen -t ed25519 -C "github-actions-deploy"
# 2. Add the public key (~/.ssh/id_ed25519.pub) to ~/.ssh/authorized_keys on your AWS server
# 3. Add the private key (~/.ssh/id_ed25519) as AWS_SSH_PRIVATE_KEY in your GitHub repo secrets
# 4. Add AWS_HOST and AWS_USER as secrets as well
# --- 